site_name: fmusim
site_url: https://modelica.github.io/fmusim
repo_name: fmusim
repo_url: https://github.com/modelica/fmusim
nav:
  - Home: index.md
  - Tutorial: tutorial.md
theme:
  name: material
  logo: assets/FMI-bare.svg
  favicon: assets/favicon.ico
  features:
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
